/** Auto-generated by scripts/sync-review-avatar-manifest.mjs — do not edit manually */
export const REVIEW_AVATAR_FILES = [
  "avatar-01.webp",
  "avatar-02.webp",
  "avatar-03.webp",
  "avatar-04.webp",
  "avatar-05.webp",
  "avatar-06.webp",
  "avatar-07.webp",
  "avatar-08.webp",
  "avatar-09.webp",
  "avatar-10.webp",
  "avatar-11.webp",
  "avatar-12.webp",
  "avatar-13.webp",
  "avatar-14.webp",
  "avatar-15.webp",
  "avatar-16.webp",
  "avatar-17.webp",
  "avatar-18.webp",
  "avatar-19.webp",
  "avatar-20.webp"
] as const;

export type ReviewAvatarFile = (typeof REVIEW_AVATAR_FILES)[number];
