"use client";

import { FormEvent, useCallback, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowDown, ArrowUp, Loader2, Pencil, Plus, Search, Trash2, X } from "lucide-react";
import { cn } from "@/lib/utils";
import { PortfolioImage } from "@/components/Portfolio/PortfolioImage";
import { ImageUploadDropzone } from "@/components/ui/image-upload-dropzone";
import { AdminToast } from "@/components/ui/admin-toast";
import {
  portfolioCategoryOptions,
  portfolioCategories,
  formatPortfolioDate,
  inputValueToPortfolioDate,
  portfolioDateToInputValue,
  type PortfolioCategory,
  type PortfolioItem,
} from "@/components/Portfolio/portfolio-data";
import { usePortfolioItems } from "@/hooks/use-portfolio-store";
import { deleteStoredImage, isStoredImageRef } from "@/lib/local-image-store";
import {
  createPortfolioItem,
  deletePortfolioItem,
  reorderPortfolioItem,
  updatePortfolioItem,
} from "@/lib/portfolio-store";
import {
  generatePortfolioAutoApi,
  generatePortfolioDescriptionApi,
  portfolioAiErrorMessage,
} from "@/lib/api/portfolio-ai-client";
import { analyzePortfolioImageFromSrc } from "@/lib/ai/analyze-portfolio-image";
import { fetchStyleMemoryStatus } from "@/lib/api/style-memory-client";
import { resolveImageSrc } from "@/lib/local-image-store";
import { filterPortfolioItems } from "@/lib/portfolio-search";
import {
  formatPortfolioTagsInput,
  parsePortfolioTagsInput,
} from "@/lib/portfolio-tags";

const inputClass =
  "h-11 w-full rounded-[14px] border border-artdear-border-strong bg-background px-4 text-[14px] text-artdear-text outline-none transition-colors duration-300 focus:border-artdear-purple focus:ring-2 focus:ring-artdear-purple/20";

type FormState = {
  title: string;
  description: string;
  tagsInput: string;
  category: PortfolioCategory;
  date: string;
  imageUrl: string | null;
};

const emptyForm: FormState = {
  title: "",
  description: "",
  tagsInput: "",
  category: "게임 포스터",
  date: portfolioDateToInputValue(formatPortfolioDate()),
  imageUrl: null,
};

function PortfolioFormModal({
  mode,
  initial,
  onClose,
  onSaved,
}: {
  mode: "create" | "edit";
  initial?: PortfolioItem;
  onClose: () => void;
  onSaved: () => void;
}) {
  const router = useRouter();
  const [form, setForm] = useState<FormState>(() =>
    initial
      ? {
          title: initial.title,
          description: initial.description,
          tagsInput: formatPortfolioTagsInput(initial.tags),
          category: initial.category,
          date: portfolioDateToInputValue(initial.date) || portfolioDateToInputValue(formatPortfolioDate()),
          imageUrl: initial.imageUrl ?? null,
        }
      : emptyForm
  );
  const [error, setError] = useState("");
  const [descriptionLoading, setDescriptionLoading] = useState(false);
  const [autoGenerateLoading, setAutoGenerateLoading] = useState(false);
  const [autoGenerateStep, setAutoGenerateStep] = useState("");
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [toastMessage, setToastMessage] = useState("");
  const [toastVisible, setToastVisible] = useState(false);

  const showToast = useCallback((message: string) => {
    setToastMessage(message);
    setToastVisible(true);
  }, []);

  const representativeImageUrl = form.imageUrl ?? initial?.imageUrl ?? null;

  const handleAutoGeneratePortfolio = async (regenerate = false) => {
    setError("");

    if (!representativeImageUrl) {
      showToast("대표 이미지를 먼저 업로드해주세요.");
      return;
    }

    const hasExistingContent =
      form.title.trim() || form.description.trim() || form.tagsInput.trim();

    if (hasExistingContent && !regenerate && !window.confirm("기존 입력값을 덮어쓰시겠습니까?")) {
      return;
    }

    setAutoGenerateLoading(true);
    setAutoGenerateStep("이미지 분석 중...");

    try {
      const imageSrc = resolveImageSrc(representativeImageUrl);
      if (!imageSrc) {
        showToast("대표 이미지를 먼저 업로드해주세요.");
        return;
      }

      const imageAnalysis = await analyzePortfolioImageFromSrc(imageSrc);

      setAutoGenerateStep("포트폴리오 생성 중...");

      const result = await generatePortfolioAutoApi({
        imageUrl: representativeImageUrl,
        imageAnalysis,
      });

      setForm((prev) => ({
        ...prev,
        title: result.title,
        description: result.description,
        tagsInput: formatPortfolioTagsInput(result.tags),
        category: result.category as PortfolioCategory,
      }));

      setHasAutoGenerated(true);
      showToast("포트폴리오가 자동 생성되었습니다.");
    } catch (err) {
      const code = err instanceof Error ? err.message : "generation_failed";
      setError(portfolioAiErrorMessage(code));
    } finally {
      setAutoGenerateLoading(false);
      setAutoGenerateStep("");
    }
  };

  const handleGenerateDescription = async () => {
    setError("");

    if (!form.title.trim()) {
      setError("제목을 입력해주세요.");
      return;
    }
    if (form.description.trim() && !window.confirm("기존 설명을 덮어쓰시겠습니까?")) {
      return;
    }

    setDescriptionLoading(true);
    try {
      const { description } = await generatePortfolioDescriptionApi({
        title: form.title.trim(),
        category: form.category,
        tags: parsePortfolioTagsInput(form.tagsInput),
        imageUrl: representativeImageUrl,
      });
      setForm((prev) => ({
        ...prev,
        description,
      }));
      showToast("설명이 자동 생성되었습니다.");
    } catch (err) {
      setError(
        portfolioAiErrorMessage(err instanceof Error ? err.message : "generation_failed")
      );
    } finally {
      setDescriptionLoading(false);
    }
  };

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    if (!form.title.trim()) {
      setError("제목을 입력해주세요.");
      return;
    }
    if (!form.description.trim()) {
      setError("설명을 입력해주세요.");
      return;
    }
    if (!form.imageUrl && !initial?.image) {
      setError("이미지를 업로드해주세요.");
      return;
    }

    if (!form.date) {
      setError("작업일을 입력해주세요.");
      return;
    }

    const payload = {
      title: form.title.trim(),
      description: form.description.trim(),
      tags: parsePortfolioTagsInput(form.tagsInput),
      category: form.category,
      date: inputValueToPortfolioDate(form.date),
      imageUrl: form.imageUrl,
      image: form.imageUrl ? undefined : initial?.image,
    };

    try {
      if (mode === "create") {
        await createPortfolioItem(payload);
        try {
          const styleStatus = await fetchStyleMemoryStatus();
          if (
            styleStatus.isTrained &&
            styleStatus.needsRetrain &&
            window.confirm(
              "새로운 포트폴리오가 추가되었습니다. 다시 학습하시겠습니까?"
            )
          ) {
            router.push("/admin/style-training");
          }
        } catch {
          // style memory status is optional
        }
      } else if (initial) {
        if (
          isStoredImageRef(initial.imageUrl) &&
          initial.imageUrl !== form.imageUrl
        ) {
          await deleteStoredImage(initial.imageUrl);
        }
        await updatePortfolioItem(initial.id, payload);
      }

      onSaved();
      onClose();
    } catch {
      setError("저장에 실패했습니다.");
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <button
        type="button"
        aria-label="닫기"
        className="absolute inset-0 bg-black/40 backdrop-blur-sm"
        onClick={onClose}
      />
      <div className="relative z-10 max-h-[90vh] w-full max-w-[560px] overflow-y-auto rounded-[22px] bg-artdear-card p-6 shadow-[0_24px_64px_-16px_rgba(0,0,0,0.25)] sm:p-8">
        <div className="flex items-center justify-between">
          <h2 className="text-[18px] font-bold text-artdear-text">
            {mode === "create" ? "포트폴리오 추가" : "포트폴리오 수정"}
          </h2>
          <button
            type="button"
            onClick={onClose}
            className="flex size-8 items-center justify-center rounded-full text-artdear-text-subtle hover:bg-artdear-panel"
          >
            <X className="size-5" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="mt-6 space-y-4">
          {form.imageUrl ? (
            <ImageUploadDropzone
              label="이미지"
              value={form.imageUrl}
              onChange={(imageUrl) => setForm((p) => ({ ...p, imageUrl }))}
            />
          ) : initial && !form.imageUrl ? (
            <div>
              <p className="mb-1.5 text-[13px] font-medium text-artdear-text-muted">이미지</p>
              <div className="relative aspect-[4/3] overflow-hidden rounded-[16px] border border-artdear-border-card bg-artdear-panel">
                <PortfolioImage item={initial} className="object-cover" />
              </div>
              <div className="mt-3">
                <ImageUploadDropzone
                  value={null}
                  onChange={(imageUrl) => setForm((p) => ({ ...p, imageUrl }))}
                  emptyText="새 이미지 업로드 (드래그 앤 드롭)"
                />
              </div>
            </div>
          ) : (
            <ImageUploadDropzone
              label="이미지"
              value={form.imageUrl}
              onChange={(imageUrl) => setForm((p) => ({ ...p, imageUrl }))}
            />
          )}

          {representativeImageUrl ? (
            <div className="space-y-2">
              <div className="flex flex-col gap-2 sm:flex-row">
                <button
                  type="button"
                  onClick={() => void handleAutoGeneratePortfolio(false)}
                  disabled={autoGenerateLoading || descriptionLoading}
                  className="inline-flex h-10 flex-1 items-center justify-center gap-2 rounded-full border border-artdear-border-strong bg-artdear-btn-secondary text-[13px] font-semibold text-artdear-purple transition-colors hover:border-artdear-purple hover:bg-artdear-purple-light disabled:cursor-not-allowed disabled:opacity-60"
                >
                  {autoGenerateLoading ? (
                    <Loader2 className="size-4 animate-spin" aria-hidden="true" />
                  ) : (
                    <span aria-hidden="true">✨</span>
                  )}
                  AI 포트폴리오 생성
                </button>
                <button
                  type="button"
                  onClick={() => void handleAutoGeneratePortfolio(true)}
                  disabled={autoGenerateLoading || descriptionLoading || !hasAutoGenerated}
                  className="inline-flex h-10 shrink-0 items-center justify-center rounded-full border border-artdear-border-strong px-4 text-[13px] font-semibold text-artdear-text-subtle transition-colors hover:border-artdear-purple hover:text-artdear-purple disabled:cursor-not-allowed disabled:opacity-60"
                >
                  다시 생성
                </button>
              </div>
              {autoGenerateLoading && autoGenerateStep ? (
                <p className="text-center text-[12px] text-artdear-text-subtle">{autoGenerateStep}</p>
              ) : null}
            </div>
          ) : null}

          <div>
            <label htmlFor="pf-title" className="mb-1.5 block text-[13px] font-medium text-artdear-text-muted">
              제목
            </label>
            <input
              id="pf-title"
              value={form.title}
              onChange={(e) => setForm((p) => ({ ...p, title: e.target.value }))}
              className={inputClass}
            />
          </div>

          <div>
            <label htmlFor="pf-tags" className="mb-1.5 block text-[13px] font-medium text-artdear-text-muted">
              태그(Tag)
            </label>
            <input
              id="pf-tags"
              value={form.tagsInput}
              onChange={(e) => setForm((p) => ({ ...p, tagsInput: e.target.value }))}
              placeholder="키링, 귀여움, 파스텔 또는 #키링 #귀여움 #파스텔"
              className={inputClass}
            />
            <p className="mt-1.5 text-[12px] text-artdear-text-light">
              쉼표 또는 #으로 구분해 입력합니다. 저장 시 태그 배열로 저장됩니다.
            </p>
          </div>

          <div>
            <div className="mb-1.5 flex items-center justify-between gap-3">
              <label htmlFor="pf-desc" className="text-[13px] font-medium text-artdear-text-muted">
                설명
              </label>
              <button
                type="button"
                onClick={() => void handleGenerateDescription()}
                disabled={descriptionLoading}
                className="inline-flex h-8 shrink-0 items-center gap-1.5 rounded-full border border-artdear-border-strong bg-artdear-btn-secondary px-3.5 text-[12px] font-semibold text-artdear-purple transition-colors hover:border-artdear-purple hover:bg-artdear-purple-light disabled:cursor-not-allowed disabled:opacity-60"
              >
                {descriptionLoading ? (
                  <Loader2 className="size-3.5 animate-spin" aria-hidden="true" />
                ) : (
                  <span aria-hidden="true">✨</span>
                )}
                설명 자동 생성
              </button>
            </div>
            <textarea
              id="pf-desc"
              rows={4}
              value={form.description}
              onChange={(e) => setForm((p) => ({ ...p, description: e.target.value }))}
              className="w-full resize-none rounded-[14px] border border-artdear-border-strong bg-background px-4 py-3 text-[14px] text-artdear-text outline-none focus:border-artdear-purple focus:ring-2 focus:ring-artdear-purple/20"
            />
          </div>

          <div>
            <label htmlFor="pf-cat" className="mb-1.5 block text-[13px] font-medium text-artdear-text-muted">
              카테고리
            </label>
            <select
              id="pf-cat"
              value={form.category}
              onChange={(e) =>
                setForm((p) => ({ ...p, category: e.target.value as PortfolioCategory }))
              }
              className={inputClass}
            >
              {portfolioCategoryOptions.map((cat) => (
                <option key={cat} value={cat}>
                  {cat}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label htmlFor="pf-date" className="mb-1.5 block text-[13px] font-medium text-artdear-text-muted">
              작업일
            </label>
            <input
              id="pf-date"
              type="date"
              value={form.date}
              onChange={(e) => setForm((p) => ({ ...p, date: e.target.value }))}
              className={inputClass}
            />
            <p className="mt-1.5 text-[12px] text-artdear-text-light">
              YYYY.MM.DD 형식으로 저장됩니다.
            </p>
          </div>

          {error ? (
            <p className="text-[13px] text-red-500" role="alert">
              {error}
            </p>
          ) : null}

          <button
            type="submit"
            className="h-11 w-full rounded-full bg-artdear-purple text-[15px] font-semibold text-white shadow-[var(--shadow-artdear-btn)] hover:bg-artdear-purple-dark"
          >
            저장
          </button>
        </form>

        <AdminToast
          message={toastMessage}
          visible={toastVisible}
          onClose={() => setToastVisible(false)}
        />
      </div>
    </div>
  );
}

function DeleteConfirmModal({
  item,
  loading,
  onCancel,
  onConfirm,
}: {
  item: PortfolioItem;
  loading: boolean;
  onCancel: () => void;
  onConfirm: () => void;
}) {
  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center p-4">
      <button
        type="button"
        aria-label="닫기"
        className="absolute inset-0 bg-black/40 backdrop-blur-sm"
        onClick={loading ? undefined : onCancel}
      />
      <div
        role="alertdialog"
        aria-modal="true"
        aria-labelledby="portfolio-delete-title"
        className="relative z-10 w-full max-w-[420px] rounded-[22px] bg-artdear-card p-6 shadow-[0_24px_64px_-16px_rgba(0,0,0,0.25)] sm:p-8"
      >
        <h2 id="portfolio-delete-title" className="text-[18px] font-bold text-artdear-text">
          포트폴리오 삭제
        </h2>
        <p className="mt-3 text-[14px] leading-relaxed text-artdear-text-subtle">
          <span className="font-semibold text-artdear-text">"{item.title}"</span> 작품을
          삭제하시겠습니까?
        </p>
        <div className="mt-6 flex gap-3">
          <button
            type="button"
            disabled={loading}
            onClick={onCancel}
            className="inline-flex h-11 flex-1 items-center justify-center rounded-full border border-artdear-border-strong bg-artdear-btn-secondary text-[14px] font-semibold text-artdear-text-muted transition-colors hover:border-artdear-purple hover:text-artdear-purple disabled:opacity-60"
          >
            취소
          </button>
          <button
            type="button"
            disabled={loading}
            onClick={onConfirm}
            className="inline-flex h-11 flex-1 items-center justify-center gap-2 rounded-full bg-red-500 text-[14px] font-semibold text-white transition-colors hover:bg-red-600 disabled:opacity-60"
          >
            {loading ? <Loader2 className="size-4 animate-spin" aria-hidden="true" /> : null}
            삭제
          </button>
        </div>
      </div>
    </div>
  );
}

export function AdminPortfolioManager() {
  const { items, ready, refresh } = usePortfolioItems();
  const [modal, setModal] = useState<"create" | "edit" | null>(null);
  const [editing, setEditing] = useState<PortfolioItem | null>(null);
  const [searchQuery, setSearchQuery] = useState("");
  const [activeCategory, setActiveCategory] = useState<PortfolioCategory | "all">("all");
  const [deleteTarget, setDeleteTarget] = useState<PortfolioItem | null>(null);
  const [deleteLoading, setDeleteLoading] = useState(false);

  const filtered = useMemo(() => {
    const searched = filterPortfolioItems(items, searchQuery);
    return searched.filter((item) => activeCategory === "all" || item.category === activeCategory);
  }, [items, activeCategory, searchQuery]);

  const handleDeleteClick = (item: PortfolioItem) => {
    console.log("[portfolio-delete] delete button clicked", {
      id: item.id,
      title: item.title,
      imageUrl: item.imageUrl ?? null,
    });
    setDeleteTarget(item);
  };

  const handleDeleteConfirm = async () => {
    if (!deleteTarget) return;

    const item = deleteTarget;
    console.log("[portfolio-delete] handleDelete executed", { id: item.id, title: item.title });
    setDeleteLoading(true);

    try {
      console.log("[portfolio-delete] calling deletePortfolioItem", {
        id: item.id,
        url: `/api/admin/portfolio/${item.id}`,
      });

      const deleted = await deletePortfolioItem(item.id);
      console.log("[portfolio-delete] deletePortfolioItem response", { id: item.id, deleted });

      if (!deleted) {
        throw new Error("not_found");
      }

      if (isStoredImageRef(item.imageUrl)) {
        console.log("[portfolio-delete] cleaning up stored image", { imageUrl: item.imageUrl });
        try {
          await deleteStoredImage(item.imageUrl);
          console.log("[portfolio-delete] stored image cleanup complete", {
            imageUrl: item.imageUrl,
          });
        } catch (imageError) {
          console.warn("[portfolio-delete] stored image cleanup failed (portfolio already deleted)", {
            imageUrl: item.imageUrl,
            error: imageError,
          });
        }
      }

      console.log("[portfolio-delete] refreshing portfolio list");
      await refresh();
      console.log("[portfolio-delete] delete complete", { id: item.id });
      setDeleteTarget(null);
    } catch (error) {
      console.error("[portfolio-delete] delete failed", { id: item.id, error });
      alert("삭제에 실패했습니다.");
    } finally {
      setDeleteLoading(false);
    }
  };

  const handleReorder = async (id: string, direction: "up" | "down") => {
    try {
      await reorderPortfolioItem(id, direction);
      await refresh();
    } catch {
      alert("순서 변경에 실패했습니다.");
    }
  };

  return (
    <div>
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-[24px] font-bold text-artdear-text">포트폴리오</h1>
          <p className="mt-1 text-[14px] text-artdear-text-subtle">
            등록된 작품 {ready ? items.length : "-"}개
          </p>
        </div>
        <button
          type="button"
          onClick={() => {
            setEditing(null);
            setModal("create");
          }}
          className="inline-flex h-10 items-center justify-center gap-2 rounded-full bg-artdear-purple px-5 text-[14px] font-semibold text-white shadow-[var(--shadow-artdear-btn)] hover:bg-artdear-purple-dark"
        >
          <Plus className="size-4" />
          추가
        </button>
      </div>

      <div className="relative mt-6 max-w-md">
        <Search
          className="pointer-events-none absolute top-1/2 left-3.5 size-4 -translate-y-1/2 text-artdear-text-light"
          strokeWidth={2}
        />
        <input
          type="search"
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          placeholder="작품명, 설명, 카테고리, 태그 검색..."
          className={cn(inputClass, "pl-10")}
        />
      </div>

      <div className="mt-4 flex flex-wrap gap-2">
        {portfolioCategories.map(({ label, value }) => (
          <button
            key={value}
            type="button"
            onClick={() => setActiveCategory(value)}
            className={cn(
              "rounded-full px-4 py-1.5 text-[12px] font-medium transition-colors",
              activeCategory === value
                ? "bg-artdear-purple text-white"
                : "bg-artdear-purple-light text-artdear-purple hover:bg-artdear-purple-light-hover"
            )}
          >
            {label}
          </button>
        ))}
      </div>

      <div className="mt-6 overflow-hidden rounded-[22px] border border-artdear-border-card bg-artdear-card shadow-[var(--shadow-artdear-card)]">
        {!ready ? (
          <p className="px-6 py-12 text-center text-[14px] text-artdear-text-subtle">불러오는 중...</p>
        ) : filtered.length === 0 ? (
          <p className="px-6 py-12 text-center text-[14px] text-artdear-text-subtle">
            {searchQuery.trim() || activeCategory !== "all"
              ? "검색 결과가 없습니다."
              : "등록된 작품이 없습니다."}
          </p>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full min-w-[800px] text-left text-[13px]">
              <thead className="border-b border-artdear-border-card bg-artdear-panel">
                <tr>
                  <th className="px-6 py-3 font-semibold text-artdear-text-muted">순서</th>
                  <th className="px-6 py-3 font-semibold text-artdear-text-muted">미리보기</th>
                  <th className="px-6 py-3 font-semibold text-artdear-text-muted">작업명</th>
                  <th className="px-6 py-3 font-semibold text-artdear-text-muted">카테고리</th>
                  <th className="px-6 py-3 font-semibold text-artdear-text-muted">작업일</th>
                  <th className="px-6 py-3 font-semibold text-artdear-text-muted">관리</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-artdear-border-card">
                {filtered.map((item) => {
                  const globalIndex = items.findIndex((i) => i.id === item.id);
                  return (
                    <tr key={item.id} className="hover:bg-artdear-panel">
                      <td className="px-6 py-3">
                        <div className="flex items-center gap-1">
                          <button
                            type="button"
                            disabled={globalIndex === 0}
                            onClick={() => handleReorder(item.id, "up")}
                            className="flex size-7 items-center justify-center rounded-[8px] text-artdear-purple hover:bg-artdear-purple-light disabled:opacity-30"
                            aria-label="위로"
                          >
                            <ArrowUp className="size-4" />
                          </button>
                          <button
                            type="button"
                            disabled={globalIndex === items.length - 1}
                            onClick={() => handleReorder(item.id, "down")}
                            className="flex size-7 items-center justify-center rounded-[8px] text-artdear-purple hover:bg-artdear-purple-light disabled:opacity-30"
                            aria-label="아래로"
                          >
                            <ArrowDown className="size-4" />
                          </button>
                        </div>
                      </td>
                      <td className="px-6 py-3">
                        <div className="relative size-14 overflow-hidden rounded-[10px] bg-artdear-panel">
                          <PortfolioImage item={item} className="object-cover" />
                        </div>
                      </td>
                      <td className="px-6 py-3 font-medium text-artdear-text">{item.title}</td>
                      <td className="px-6 py-3 text-artdear-purple">{item.category}</td>
                      <td className="px-6 py-3 text-artdear-text-subtle">{item.date}</td>
                      <td className="px-6 py-3">
                        <div className="flex items-center gap-2">
                          <button
                            type="button"
                            onClick={() => {
                              setEditing(item);
                              setModal("edit");
                            }}
                            className="flex size-8 items-center justify-center rounded-[10px] text-artdear-purple hover:bg-artdear-purple-light"
                            aria-label="수정"
                          >
                            <Pencil className="size-4" />
                          </button>
                          <button
                            type="button"
                            onClick={(event) => {
                              event.preventDefault();
                              event.stopPropagation();
                              handleDeleteClick(item);
                            }}
                            className="flex size-8 items-center justify-center rounded-[10px] text-red-500 hover:bg-red-50"
                            aria-label="삭제"
                          >
                            <Trash2 className="size-4" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {modal ? (
        <PortfolioFormModal
          mode={modal}
          initial={editing ?? undefined}
          onClose={() => {
            setModal(null);
            setEditing(null);
          }}
          onSaved={refresh}
        />
      ) : null}

      {deleteTarget ? (
        <DeleteConfirmModal
          item={deleteTarget}
          loading={deleteLoading}
          onCancel={() => {
            if (deleteLoading) return;
            console.log("[portfolio-delete] delete cancelled", { id: deleteTarget.id });
            setDeleteTarget(null);
          }}
          onConfirm={() => void handleDeleteConfirm()}
        />
      ) : null}
    </div>
  );
}
